# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_cover', models.CharField(max_length=1000)),
                ('a_resume', models.FileField(upload_to='media/resume/')),
                ('a_created', models.DateTimeField(auto_now=True)),
                ('a_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employer.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_detail', models.CharField(max_length=5000)),
                ('r_created', models.DateTimeField(auto_now=True)),
                ('r_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employer.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_qualification', models.CharField(max_length=200)),
                ('s_experience', models.CharField(max_length=200)),
                ('s_ph', models.IntegerField()),
                ('s_resume', models.FileField(null=True, upload_to='media/resume/')),
                ('s_image', models.ImageField(null=True, upload_to='media/image/')),
                ('s_created', models.DateTimeField(auto_now=True)),
                ('s_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='r_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jobseeker.Seeker'),
        ),
        migrations.AddField(
            model_name='application',
            name='a_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobseeker.Seeker'),
        ),
    ]
