# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='a_cover',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='s_experience',
            field=models.TextField(max_length=200),
        ),
    ]
