# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-12 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_auto_20180512_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
