# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
