# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-24 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_firm', models.CharField(max_length=50)),
                ('e_detail', models.CharField(max_length=5000)),
                ('e_place', models.CharField(max_length=50)),
                ('e_created', models.DateTimeField(auto_now=True)),
                ('e_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_name', models.CharField(max_length=50)),
                ('j_detail', models.CharField(max_length=5000)),
                ('j_requirement', models.CharField(max_length=5000)),
                ('j_created', models.DateTimeField(auto_now=True)),
                ('j_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('s_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='employer.Category')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='j_subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employer.SubCategory'),
        ),
    ]
