# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='e_detail',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='j_detail',
            field=models.TextField(max_length=5000),
        ),
    ]
