# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20180525_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='e_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to=settings.AUTH_USER_MODEL),
        ),
    ]
