# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20180526_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='j_requirement',
            field=models.TextField(max_length=5000),
        ),
    ]
