# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20180526_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='j_salary',
            field=models.IntegerField(null=True),
        ),
    ]
