# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=3)),
                ('place', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_brand', models.CharField(max_length=200)),
                ('pro_detail', models.TextField(max_length=500)),
                ('pro_size', models.CharField(choices=[('8', 'Small'), ('9', 'Medium'), ('10', 'Large'), ('11', 'XLarge')], max_length=4)),
                ('pro_image', models.ImageField(upload_to='image/')),
                ('pro_color', models.CharField(max_length=200)),
                ('pro_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='footshop.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='footshop.SubCategory'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='footshop.Customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footshop.Product'),
        ),
    ]
