# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(),
        ),
    ]
