# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footshop', '0002_auto_20180519_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
