# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footshop', '0002_auto_20180521_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footshop.Customer'),
        ),
    ]
